runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: app/static

- url: /favicon.ico
  static_files: app/static/favicons/favicon.ico
  upload: app/static/favicons/favicon.ico

- url: /.*
  script: app.main.app

libraries:
- name: jinja2
  version: latest
