runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicons/favicon.ico
  upload: static/favicons/favicon.ico

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
